#!/bin/sh

echo "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"
echo "Unpack last build"
./scripts/unpack

echo "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"
echo "Building Lambda Functions"
./node_modules/.bin/netlify-lambda build ./functions

echo "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"
echo "Generating Sqip previews"
NODE_ENV=production ./scripts/sqip-it

echo "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"
echo "Generating Static Site"
NODE_ENV=production ./node_modules/.bin/nuxt generate

echo "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"
echo "Move sqip cache into public for next runs"
cp -r ./.archive/old-dist/.sqip ./dist/.sqip

echo "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"
echo "Validating Markup"
./scripts/check-markup

echo "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"
echo "Creating RSS Feeds"
./scripts/create-rss-feed

echo "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐"
echo "Archive dist folder"
./scripts/pack
