#!/bin/sh

echo "⭐⭐⭐"
echo "BUILD TRIGGERED BY:"
echo "$WEBHOOK_TITLE"

# echo "⭐⭐⭐"
# echo "Building Lambda Functions"
# npm run function:build

echo "⭐⭐⭐"
echo "Making sure dist exists"
if [ ! -d "./dist" ]; then
  echo "Creating new dist directory"
  mkdir ./dist
fi

echo "⭐⭐⭐"
echo "Generating Sqip previews"
echo ""
./scripts/sqip-it

echo "⭐⭐⭐"
echo "Writing analytics data"
echo ""
./scripts/write-analytics-data

echo "⭐⭐⭐"
echo "Generating Static Site"
echo ""
./scripts/generate

echo "⭐⭐⭐"
echo "Validating Markup"
echo ""
./scripts/check-markup

echo "⭐⭐⭐"
echo "Creating RSS Feeds"
echo ""
./scripts/create-rss-feed
