#!/usr/bin/env node

const { Nuxt, Builder, Generator } = require('nuxt')
const config = require('../nuxt.config.js')

config.mode = 'universal'
config.dev = false

const nuxt = new Nuxt(config)
const builder = new Builder(nuxt)
const generator = new Generator(nuxt, builder)
const generateOptions = {
  init: true, // process.env.WEBHOOK_TITLE === 'CLEAR_CUSTOM_CACHE',
  build: true
}

async function generateRoutes () {
  try {
    await generator.generate(generateOptions)
  } catch (e) {
    console.error(e)
  }
}

generateRoutes()
