#!/usr/bin/env node

const contentful = require('contentful');
const sqip = require('sqip');
const download = require('download');
const path = require('path');
const { emptyDir, writeFile, readFile } = require('fs-extra');
const { logSeparator, logSuccess, writeData } = require('./utils');

const { getConfig } = require('../lib/config.js');
const { CTF_SPACE_ID, CTF_CDA_TOKEN } = getConfig();
const client = contentful.createClient({
  accessToken: CTF_CDA_TOKEN,
  host: 'cdn.contentful.com',
  space: CTF_SPACE_ID
});

const { getCachePath, shouldClearCache } = require('./utils/index.js');
const SQIP_CACHE = getCachePath('sqip');

async function sqipItems() {
  if (shouldClearCache) {
    logSeparator(`Clearing ${SQIP_CACHE}`);
    await emptyDir(SQIP_CACHE);
    logSuccess('SQIP cached deleted');
  }

  logSeparator('Getting asset information');

  const { items } = await client.getAssets({ limit: 1000 });
  let images = items
    .filter(
      ({ fields }) =>
        fields.file &&
        ['image/png', 'image/jpeg'].indexOf(fields.file.contentType) !== -1
    )
    .map(({ sys, fields }) => ({
      id: sys.id,
      revision: sys.revision,
      url: fields.file.url,
      filename: `${sys.id}-${sys.revision}.${
        fields.file.contentType.split('/')[1]
      }`,
      svg: null
    }));

  logSuccess('Asset information queried');
  logSeparator(`Reading cached SVGs from at ${SQIP_CACHE}`);

  images = await Promise.all(
    images.map(async image => {
      try {
        const svg = await readFile(
          `${SQIP_CACHE}/${image.id}-${image.revision}.svg`,
          'utf8'
        );
        if (svg.startsWith('<svg')) {
          image.svg = svg;
        }
      } catch (e) {}

      return image;
    })
  );

  logSuccess('Cached SVGs read');
  logSeparator('Downloading images for missing SVGs');

  await Promise.all(
    images.map(({ url, filename, svg }) => {
      if (!svg) {
        console.log(`${filename} is missing -> downloading`);
        return download(url.replace(/\/\//, 'https://'), SQIP_CACHE, {
          filename
        });
      }

      return Promise.resolve();
    })
  );

  logSuccess('Images downloaded');
  logSeparator('Creating missing SVGs');

  await Promise.all(
    images.map(({ id, revision, filename, svg }) => {
      if (!svg) {
        const { final_svg } = sqip({
          filename: path.join(SQIP_CACHE, filename),
          numberOfPrimitives: 8,
          mode: 0,
          blur: 0
        });

        return writeFile(
          path.join(SQIP_CACHE, `${id}-${revision}.svg`),
          final_svg
        );
      }

      return Promise.resolve();
    })
  );

  logSuccess('SVGs created');
}

sqipItems();
