#!/usr/bin/env node

const contentful = require('contentful')
const { getConfigForKeys } = require('../lib/config.js')
const {
  CTF_SPACE_ID,
  CTF_CDA_TOKEN,
  CTF_CPA_TOKEN
} = getConfigForKeys([
  'CTF_SPACE_ID',
  'CTF_CDA_TOKEN',
  'CTF_CPA_TOKEN'
])
const {exec} = require('child_process')
const download = require('download')
const path = require('path')
const {promisify} = require('util')
const {writeFile, readFile} = require('fs')
const timeSpan = require('time-span')
// const fetch = require('node-fetch')

const SQIP_CACHE = path.resolve(__dirname, '..', 'dist', 'sqip')
const JS_DESTINATION = path.resolve(__dirname, '..', 'plugins', 'image-map.js')
const SQIP_EXEC = path.resolve(__dirname, '..', 'node_modules', '.bin', 'sqip')

const ora = require('ora')

const client = contentful.createClient({
  accessToken:
    process.env.NODE_ENV === 'production'
      ? CTF_CDA_TOKEN
      : CTF_CPA_TOKEN,
  host:
    process.env.NODE_ENV === 'production'
      ? 'cdn.contentful.com'
      : 'preview.contentful.com',
  space: CTF_SPACE_ID
})

const spinner = ora({spinner: 'dots12'})

const write = promisify(writeFile)
const read = promisify(readFile)
const execute = promisify(exec)

async function sqipItems () {
  const end = timeSpan()

  // --------------------------------------------

  spinner.text = 'Getting asset information'
  spinner.start()
  const {items} = await client.getAssets({limit: 1000})
  let images = items
    .filter(
      ({fields}) => fields.file && ['image/png', 'image/jpeg'].indexOf(fields.file.contentType) !== -1
    )
    .map(({sys, fields}) => ({
      id: sys.id,
      url: fields.file.url,
      filename: `${sys.id}.${fields.file.contentType.split('/')[1]}`,
      svg: null
    }))
  spinner.succeed('Asset information queried')

  // --------------------------------------------

  if (process.env.WEBHOOK_TITLE === 'CLEAR_CUSTOM_CACHE') {
    spinner.text = 'Clear webhook detected - skipping cached SVGs'
  } else {
    spinner.text = 'Reading cached SVGs'
    spinner.start()
    images = await Promise.all(images.map(async (image) => {
      try {
        const svg = await read(`${SQIP_CACHE}/${image.id}.svg`, 'utf8')
        if (svg.startsWith('<svg')) {
          image.svg = svg
        }
      } catch (e) {}

      return image
    }))
    spinner.succeed('Cached SVGs downloaded')
  }

  // --------------------------------------------

  spinner.text = 'Downloading images for missing SVGs...'
  spinner.start()
  await Promise.all(
    images.map(({url, filename, svg}) => {
      if (!svg) {
        console.log(`${filename} is missing -> downloading`)
        return download(
          url.replace(/\/\//, 'https://'),
          SQIP_CACHE,
          { filename }
        )
      }

      return Promise.resolve()
    })
  )
  spinner.succeed('Images downloaded')

  // --------------------------------------------

  spinner.text = 'Creating missing SVGs...'
  spinner.start()
  await Promise.all(images.map(({id, filename, svg}) => {
    if (!svg) {
      const command = `${SQIP_EXEC} -o ${id}.svg -n 15 -m 0 -b 0 ${filename}`

      return execute(
        command,
        {cwd: SQIP_CACHE}
      )
    }

    return Promise.resolve()
  }))
  spinner.succeed('SVGs created')

  // --------------------------------------------

  spinner.text = 'Reading missing SVGs...'
  spinner.start()
  images = await Promise.all(images.map(async (image) => {
    if (!image.svg) {
      const svg = await read(path.join(SQIP_CACHE, `${image.id}.svg`), 'utf8')
      image.svg = svg.replace('<svg', `<svg id="image.id"`)
    }

    return image
  }))
  spinner.succeed('SVGs read')

  // --------------------------------------------

  spinner.text = 'Writing JS mapping file'
  spinner.start()
  write(
    JS_DESTINATION,
    `export default {\n  ${images.map(({id, svg}) => `'${id}': '${svg}'`).join(', ')}\n}\n`
  )
  spinner.succeed('JS file written')

  // --------------------------------------------

  console.log(end.seconds())
}

sqipItems()
