#!/bin/bash

if [ "$WEBHOOK_TITLE" = CLEAR_CUSTOM_CACHE ]; then
  echo "Clear webhook detected - skipping unpacking archive"
else
  rm -rf ./dist/*
  mkdir ./dist/archive/

  wget -qO- -O ./dist/archive/tmp.zip https://www.stefanjudis.com/archive/index.zip && unzip ./dist/archive/tmp.zip -d ./dist && rm dist/archive/tmp.zip
  mv  dist/dist/* dist
  rm -r dist/dist
fi
