#!/usr/bin/env node

require('dotenv').config();
const { queryContentful, queryGithub } = require('../lib/graphql');
const camelcase = require('camelcase');
const { logSeparator, logSuccess, writeDataFile } = require('./utils');
const hasTopicToBeIncluded = (project) =>
  project.repositoryTopics.nodes.some(
    ({ topic }) => topic.name === 'show-on-my-website'
  );
const filterDuplicateRepositories = (repos) =>
  repos.reduce(
    (acc, cur) => {
      if (!acc.set.has(cur.name)) {
        acc.set.add(cur.name);
        acc.collection.push(cur);
      }

      return acc;
    },
    { set: new Set(), collection: [] }
  ).collection;

const query = `
{
  user(login: "stefanjudis") {
    repositories(first: 15, orderBy: {field: STARGAZERS, direction: DESC}, ownerAffiliations: OWNER) {
      nodes {
        ...Repo
      }
    }
    pinnedItems(first: 6) {
      nodes {
        ... on Repository {
          ...Repo
        }
      }
    }
  }
}

fragment Repo on Repository {
  name
  description
  url
  pushedAt
  repositoryTopics(first: 8) {
    nodes {
      topic {
        name
      }
    }
  }
  description
  collaborators {
    totalCount
  }
  stargazers {
    totalCount
  }
  forks {
    totalCount
  }
}
`;

async function getGitHubProjects() {
  const { data } = await queryContentful(getProjectQuery());
  return data.projectCollection.items.filter((project) =>
    project.githubUrl?.startsWith('https://github.com')
  );
}

async function getData() {
  try {
    logSeparator('Fetching GitHub data');

    let { repositories, pinnedItems } = (await queryGithub(query)).data.user;

    console.log(repositories.nodes);

    const projects = filterDuplicateRepositories([
      ...pinnedItems.nodes,
      ...repositories.nodes.filter(hasTopicToBeIncluded),
    ]).sort((a, b) =>
      a.stargazers.totalCount > b.stargazers.totalCount ? -1 : 1
    );

    logSuccess('Data fetched');
    logSeparator('Writing JSON data file');

    writeDataFile('_githubProjects.json', JSON.stringify(projects));

    logSuccess('JSON file written');
  } catch (e) {
    console.error(e);
    process.exit(1);
  }
}

getData();
